apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootapp1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springbootapp1
  template:
    metadata:
      labels:
        app: springbootapp1
    spec:
      containers:
      - name: springbootapp0
        image: jailonso/springbootapp1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9393
---
apiVersion: v1
kind: Service
metadata:
  name: springbootapp1
spec:
  selector:
    app: springbootapp1
  ports:
  - name: http
    protocol: TCP
    port: 9494
  type: LoadBalancer
